# Generated by Django 3.2.13 on 2022-07-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220602_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationDevice',
        ),
    ]
