# Generated by Django 3.2.13 on 2022-10-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20221010_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='user_id',
            new_name='user',
        ),
    ]
