# Generated by Django 3.2.13 on 2022-06-02 08:08

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={},
        ),
        migrations.RenameField(
            model_name='cook',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cook',
            name='food_cert',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler),
        ),
        migrations.AddField(
            model_name='cook',
            name='govt_cert',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler),
        ),
        migrations.AddField(
            model_name='cook',
            name='insurance_cert',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler),
        ),
        migrations.AddField(
            model_name='cook',
            name='medical_clearance',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler),
        ),
        migrations.AddField(
            model_name='cook',
            name='work_permit',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler),
        ),
        migrations.AlterModelTable(
            name='cook',
            table='table_cook',
        ),
        migrations.CreateModel(
            name='KitchenPremises',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('kitchen_premises', models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler)),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_premises', to='cook.cook')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
