# Generated by Django 3.2.13 on 2022-06-15 06:06

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_auto_20220602_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_icon', models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler)),
                ('category_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Delete')], default=1)),
            ],
            options={
                'db_table': 'table_menu_category',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Dish Title', max_length=120)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to=core.utils.upload_path_handler)),
                ('size', models.JSONField(default=list)),
                ('warning', models.CharField(choices=[('none', 'None'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('gulten_free', 'Gluten Free'), ('nuts_free', 'Nuts Free')], default=None, max_length=12)),
                ('prepare_time', models.IntegerField(help_text='Prepare time in minutes')),
                ('item_type', models.CharField(max_length=20)),
                ('nutrition_info', models.TextField(blank=True, null=True)),
                ('cultural_facts', models.TextField(blank=True, null=True)),
                ('commercial_info', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item_category', to='cook.menucategory')),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_menu_item', to='cook.cook')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'table_menu_items',
            },
        ),
        migrations.CreateModel(
            name='MenuSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prepare_time', models.IntegerField(help_text='Prepare time in minutes')),
                ('total_calories', models.DecimalField(decimal_places=3, max_digits=4)),
                ('nutrition_info', models.TextField(blank=True, null=True)),
                ('cultural_facts', models.TextField(blank=True, null=True)),
                ('commercial_info', models.TextField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_sub_items', to='cook.menuitem')),
            ],
            options={
                'db_table': 'table_menu_sub_items',
            },
        ),
    ]
