# Generated by Django 3.2.13 on 2022-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_menucategory_menuitem_menusubitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
