# Generated by Django 3.2.13 on 2022-07-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_menuitem_item_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['-id']},
        ),
    ]
