# Generated by Django 3.2.13 on 2022-07-20 07:17

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_alter_menucategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSanitizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('quatity', models.IntegerField(help_text='Total number of objects')),
                ('feedback', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[('initial', 'Initial'), ('pass', 'Pass'), ('fail', 'Fail')], default='initial')),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_sanitizing', to='cook.cook')),
            ],
            options={
                'db_table': 'table_cleaning_sanitizing',
            },
        ),
        migrations.CreateModel(
            name='CleaningSanitizingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.upload_path_handler)),
                ('feedback', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[('initial', 'Initial'), ('pass', 'Pass'), ('fail', 'Fail')], default='initial')),
                ('cleaning_sanitizing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_senitizing_images', to='cook.cleaningsanitizing')),
            ],
            options={
                'db_table': 'table_cleaning_sanitizing_images',
            },
        ),
    ]
