# Generated by Django 3.2.13 on 2022-07-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0007_cleaningsanitizing_cleaningsanitizingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningsanitizing',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
