# Generated by Django 3.2.13 on 2022-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0008_rename_quatity_cleaningsanitizing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningsanitizing',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('pass', 'Pass'), ('fail', 'Fail')], default='initial', max_length=10),
        ),
        migrations.AlterField(
            model_name='cleaningsanitizingimage',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('pass', 'Pass'), ('fail', 'Fail')], default='initial', max_length=10),
        ),
    ]
