# Generated by Django 3.2.13 on 2022-07-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0010_foodhandling_foodhandlingimage_kitchenmaintenance_kitchenmaintenanceimage_sanitaryfacility_sanitaryf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubitem',
            name='total_calories',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
