# Generated by Django 3.2.13 on 2022-07-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0011_fsccatalogue_fsccatalogueimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningsanitizingimage',
            name='cleaning_sanitizing',
        ),
        migrations.RemoveField(
            model_name='foodhandling',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='foodhandlingimage',
            name='food_handling',
        ),
        migrations.RemoveField(
            model_name='kitchenmaintenance',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='kitchenmaintenanceimage',
            name='kitchen_maintenance',
        ),
        migrations.RemoveField(
            model_name='sanitaryfacility',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='sanitaryfacilityimage',
            name='sanitary_facility',
        ),
        migrations.DeleteModel(
            name='CleaningSanitizing',
        ),
        migrations.DeleteModel(
            name='CleaningSanitizingImage',
        ),
        migrations.DeleteModel(
            name='FoodHandling',
        ),
        migrations.DeleteModel(
            name='FoodHandlingImage',
        ),
        migrations.DeleteModel(
            name='KitchenMaintenance',
        ),
        migrations.DeleteModel(
            name='KitchenMaintenanceImage',
        ),
        migrations.DeleteModel(
            name='SanitaryFacility',
        ),
        migrations.DeleteModel(
            name='SanitaryFacilityImage',
        ),
    ]
