# Generated by Django 3.2.13 on 2022-07-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0011_alter_menusubitem_total_calories'),
        ('cook', '0012_auto_20220727_1021'),
    ]

    operations = [
    ]
