# Generated by Django 3.2.13 on 2022-09-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
        ('cook', '0013_merge_20220727_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookOrderDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook_order_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('eta', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('cook', models.ForeignKey(blank=True, db_column='cook_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_order', to='cook.cook')),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_order', to='order.order')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
