# Generated by Django 3.2.13 on 2022-09-07 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0013_merge_20220727_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='avg_star_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
