# Generated by Django 3.2.13 on 2022-09-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0014_cookorderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookorderdetails',
            old_name='order_id',
            new_name='order',
        ),
    ]
