# Generated by Django 3.2.13 on 2022-09-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0014_auto_20220907_1004'),
        ('cook', '0015_rename_order_id_cookorderdetails_order'),
    ]

    operations = [
    ]
