# Generated by Django 3.2.13 on 2022-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0018_alter_cookorderdetails_cook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookorderdetails',
            name='cook_status',
            field=models.CharField(choices=[('PE', 'pending'), ('ACK', 'cook accepted order'), ('CCK', 'cook canceled order'), ('CP', 'cooking in progress'), ('RE', 'ready'), ('REP', 'ready to pickup')], default='PE', max_length=25),
        ),
    ]
