# Generated by Django 3.2.13 on 2022-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0019_alter_cookorderdetails_cook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='featured_cook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cook',
            name='near_by_cook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cook',
            name='top_cook',
            field=models.BooleanField(default=False),
        ),
    ]
