# Generated by Django 3.2.13 on 2022-09-16 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0020_auto_20220914_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='avg_star_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='cook',
            name='total_review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
