# Generated by Django 3.2.13 on 2022-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy_policy_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('policy_heading_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Term body text in english.')),
                ('policy_body_text', models.TextField(blank=True, null=True, verbose_name='Term body text in english.')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'db_table': 'table_privacy_policy',
            },
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_condition_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('term_heading_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Term body text in english.')),
                ('term_body_text', models.TextField(blank=True, null=True, verbose_name='Term body text in english.')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name': 'Term & Condition',
                'verbose_name_plural': 'Terms & Conditions',
                'db_table': 'table_term_condition',
            },
        ),
    ]
