# Generated by Django 3.2.13 on 2022-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Translate',
                'verbose_name_plural': 'Translate',
                'db_table': 'table_translate',
            },
        ),
    ]
