# Generated by Django 3.2.13 on 2022-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_translatedata_translated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedata',
            name='data',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='translatedata',
            name='translated',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
