# Generated by Django 3.2.13 on 2022-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20220930_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook_pk', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('cook_id', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'table_transalted_user',
            },
        ),
    ]
