# Generated by Django 3.2.13 on 2022-10-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_translateduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='translateduser',
            name='courier_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translateduser',
            name='courier_pk',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translateduser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translateduser',
            name='customer_pk',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
