# Generated by Django 3.2.13 on 2022-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220728_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmenuitem',
            name='save_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
