# Generated by Django 3.2.13 on 2022-09-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenImageCaptureFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'db_table': 'table_kitchenimagecapturefrequency',
            },
        ),
    ]
