# Generated by Django 3.2.13 on 2022-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_deliveryfeespaidbycook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryWiseFoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_countrywisefoodcategory',
            },
        ),
        migrations.CreateModel(
            name='FrequentKitchenOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(blank=True, null=True)),
                ('to_perform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'table_frequentkitchenoperations',
            },
        ),
        migrations.CreateModel(
            name='FSCManualAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_fscmanualanswers',
            },
        ),
        migrations.CreateModel(
            name='FSCRegulationRulebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('regulation_rule', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'table_fscregulationsrulebook',
            },
        ),
        migrations.CreateModel(
            name='KitchenEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=100, null=True)),
                ('object_analysis_attr', models.CharField(blank=True, max_length=50, null=True)),
                ('object_media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fsc_section', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'table_kitchenequipments',
            },
        ),
    ]
