# Generated by Django 3.2.13 on 2022-09-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_countrywisefoodcategory_frequentkitchenoperations_fscmanualanswers_fscregulationrulebook_kitchenequi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrywisefoodcategory',
            old_name='text',
            new_name='category',
        ),
    ]
