# Generated by Django 3.2.13 on 2022-09-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_rename_text_countrywisefoodcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('pickup_radius', models.IntegerField()),
                ('delivery_time_threshold', models.IntegerField()),
                ('delivery_radius', models.IntegerField()),
            ],
            options={
                'db_table': 'table_aggregatedorder',
            },
        ),
        migrations.CreateModel(
            name='BufferDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'table_bufferduration',
            },
        ),
        migrations.CreateModel(
            name='ConstantPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('low_value', models.IntegerField()),
                ('medium_value', models.IntegerField()),
                ('high_value', models.IntegerField()),
            ],
            options={
                'db_table': 'table_constantpay',
            },
        ),
        migrations.CreateModel(
            name='ConstantRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('minimum_range', models.IntegerField()),
                ('maximum_range', models.IntegerField()),
            ],
            options={
                'db_table': 'table_constantrange',
            },
        ),
        migrations.CreateModel(
            name='CostPerMileLoctoRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'table_costpermileloctores',
            },
        ),
        migrations.CreateModel(
            name='CostPerMileResToCus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'table_costpermilerestocus',
            },
        ),
        migrations.CreateModel(
            name='CourierDefaultSearchRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('radius', models.IntegerField()),
            ],
            options={
                'db_table': 'table_courierdefaultsearchradius',
            },
        ),
        migrations.CreateModel(
            name='DefaultCourierPositioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'table_defaultcourierpositioning',
            },
        ),
        migrations.CreateModel(
            name='DefaultMinimumSearchRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('minimum_range', models.IntegerField()),
                ('maximum_range', models.IntegerField()),
            ],
            options={
                'db_table': 'table_defaultminimumsearchrange',
            },
        ),
        migrations.CreateModel(
            name='FacialRecognitionImageCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'db_table': 'table_facialrecognitionimagecapture',
            },
        ),
        migrations.CreateModel(
            name='HotZoneIncentivePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('order_rate_hr', models.IntegerField()),
                ('incentive', models.IntegerField()),
            ],
            options={
                'db_table': 'table_hotzoneincentivepercentage',
            },
        ),
        migrations.CreateModel(
            name='MinimumDeliveryPayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('pay_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'table_minimumdeliverypayrate',
            },
        ),
        migrations.CreateModel(
            name='PaymentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_charge', models.IntegerField()),
                ('extra_charge', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'table_paymentprocessing',
            },
        ),
    ]
