# Generated by Django 3.2.13 on 2022-09-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_aggregatedorder_bufferduration_constantpay_constantrange_costpermileloctores_costpermilerestocus_cou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocessing',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='paymentprocessing',
            name='real_charge',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
