# Generated by Django 3.2.13 on 2022-09-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20220920_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimumdeliverypayrate',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
