# Generated by Django 3.2.13 on 2022-09-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_minimumdeliverypayrate_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costpermileloctores',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='costpermilerestocus',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
