# Generated by Django 3.2.13 on 2022-09-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20220920_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constantrange',
            old_name='maximum_range',
            new_name='maximum_range_distance',
        ),
        migrations.RenameField(
            model_name='constantrange',
            old_name='minimum_range',
            new_name='minimum_range_distance',
        ),
    ]
