# Generated by Django 3.2.13 on 2022-09-21 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_auto_20220920_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParametersFeaturedCook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('inspection_grade', models.CharField(max_length=1)),
                ('stars', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'table_configparametersfeaturedcook',
            },
        ),
        migrations.CreateModel(
            name='ConfigParametersNearbyCook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('inspection_grade', models.CharField(max_length=1)),
                ('stars', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'table_configparametersnearbycook',
            },
        ),
        migrations.CreateModel(
            name='ConfigParametersTopCook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('inspection_grade', models.CharField(max_length=1)),
                ('stars', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'table_configparameterstopcook',
            },
        ),
        migrations.CreateModel(
            name='ConfigParametersTopDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('inspection_grade', models.CharField(max_length=1)),
                ('stars', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'table_configparameterstopdish',
            },
        ),
        migrations.CreateModel(
            name='DeliveryFeePaidByCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cost_per_mile', models.IntegerField()),
            ],
            options={
                'db_table': 'table_deliveryfeepaidbycustomer',
            },
        ),
        migrations.CreateModel(
            name='ItemFilterByPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('minimum_price', models.IntegerField()),
                ('maximum_price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'table_itemfilterbypricerange',
            },
        ),
        migrations.CreateModel(
            name='SalesTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('PST', models.IntegerField()),
                ('GST', models.IntegerField()),
                ('HST', models.IntegerField()),
            ],
            options={
                'db_table': 'table_salextax',
            },
        ),
        migrations.CreateModel(
            name='TipsPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('minimum_rate', models.IntegerField()),
                ('medium_rate', models.IntegerField()),
                ('highest_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'table_tipspercentage',
            },
        ),
        migrations.AlterField(
            model_name='hotzoneincentivepercentage',
            name='end_time',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)]),
        ),
        migrations.AlterField(
            model_name='hotzoneincentivepercentage',
            name='incentive',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hotzoneincentivepercentage',
            name='start_time',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2359)]),
        ),
        migrations.AlterField(
            model_name='hotzoneincentivepercentage',
            name='zip_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
