# Generated by Django 3.2.13 on 2022-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20220921_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfeepaidbycustomer',
            name='cost_per_mile',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
