# Generated by Django 3.2.13 on 2022-09-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_alter_deliveryfeepaidbycustomer_cost_per_mile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CangurhuAppAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'table_cangurhuappavailability',
            },
        ),
        migrations.CreateModel(
            name='CookGradeExplaination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'table_ccookgradeexplaination',
            },
        ),
        migrations.CreateModel(
            name='MessageTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageID', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('message_text', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=100)),
                ('receiving_audience', models.CharField(max_length=100)),
                ('where_used', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'table_messagetexts',
            },
        ),
        migrations.CreateModel(
            name='PaymentRateAndConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_payment_fee', models.IntegerField()),
                ('banking_payment_constant', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'table_bankingpaymentrateandconstant',
            },
        ),
        migrations.CreateModel(
            name='PayoutRateAndConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_payout_fee', models.IntegerField()),
                ('banking_payout_constant', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'table_bankingpayoutrateandconstant',
            },
        ),
        migrations.CreateModel(
            name='SoSDangerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'table_sosdangercontact',
            },
        ),
        migrations.RemoveField(
            model_name='salestax',
            name='GST',
        ),
        migrations.RemoveField(
            model_name='salestax',
            name='HST',
        ),
        migrations.RemoveField(
            model_name='salestax',
            name='PST',
        ),
        migrations.AddField(
            model_name='salestax',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestax',
            name='hst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestax',
            name='pst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestax',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipspercentage',
            name='highest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tipspercentage',
            name='medium_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tipspercentage',
            name='minimum_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
