# Generated by Django 3.2.13 on 2022-09-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20220922_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrateandconstant',
            name='banking_payment_constant',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='paymentrateandconstant',
            name='banking_payment_fee',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
