# Generated by Django 3.2.13 on 2022-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_alter_messagetexts_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMiscParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_diner_service_charge', models.IntegerField()),
                ('spend_point_factor', models.IntegerField()),
                ('like_point_factor', models.IntegerField()),
                ('social_media_point_factor', models.IntegerField()),
                ('monetization_factor', models.IntegerField()),
                ('reward_points_threshold', models.IntegerField()),
                ('time_for_feedback_cook', models.IntegerField()),
                ('time_for_feedback_courier', models.IntegerField()),
            ],
            options={
                'db_table': 'table_customermiscparams',
            },
        ),
    ]
