# Generated by Django 3.2.13 on 2022-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_customermiscparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermiscparams',
            name='customer_diner_service_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='like_point_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='monetization_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='reward_points_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='social_media_point_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='spend_point_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='time_for_feedback_cook',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermiscparams',
            name='time_for_feedback_courier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
