# Generated by Django 3.2.13 on 2022-09-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_auto_20220923_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierGpsImmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True)),
                ('warning_msg', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'table_couriergpsimmobile',
            },
        ),
        migrations.CreateModel(
            name='CourierTimeZoneMisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_variance', models.IntegerField(blank=True, null=True)),
                ('diner_surcharge_customer', models.IntegerField(blank=True, null=True)),
                ('threshold_for_order_assigned', models.IntegerField(blank=True, null=True)),
                ('courier_reliability_min_threshold', models.IntegerField(blank=True, null=True)),
                ('courier_immobile', models.IntegerField(blank=True, null=True)),
                ('courier_makes_stop', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_couriertimezonemisc',
            },
        ),
        migrations.CreateModel(
            name='CourierTripDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True)),
                ('warning_msg', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'table_couriertripdelay',
            },
        ),
    ]
