# Generated by Django 3.2.13 on 2022-09-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_couriergpsimmobile_couriertimezonemisc_couriertripdelay'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('incr_percentage', models.IntegerField(blank=True, null=True)),
                ('decr_percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_courierreliabilityscore',
            },
        ),
    ]
