# Generated by Django 3.2.13 on 2022-09-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_courierreliabilityscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriergpsimmobile',
            name='warning_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couriertripdelay',
            name='warning_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
