# Generated by Django 3.2.13 on 2022-09-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_auto_20220926_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_all',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
