# Generated by Django 3.2.13 on 2022-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_auto_20220926_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_grade_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configparameterstopdish',
            name='td_star_all',
            field=models.BooleanField(default=False),
        ),
    ]
