# Generated by Django 3.2.13 on 2022-06-02 10:01

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        ('courier', '0002_auto_20220602_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_country', to='snippets.country'),
        ),
        migrations.AddField(
            model_name='courier',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_path_handler),
        ),
    ]
