# Generated by Django 3.2.13 on 2022-08-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_auto_20220607_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_order_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='initial', max_length=11)),
                ('eta', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('courier_id', models.ForeignKey(blank=True, db_column='courier_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_order', to='courier.courier')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
