# Generated by Django 3.2.13 on 2022-08-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_courierorder'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_order', to='order.order'),
        ),
    ]
