# Generated by Django 3.2.13 on 2022-09-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_rename_courier_id_courierorder_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierorder',
            name='status',
        ),
    ]
