# Generated by Django 3.2.13 on 2022-09-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_remove_courierorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierorder',
            old_name='order_id',
            new_name='order',
        ),
    ]
