# Generated by Django 3.2.13 on 2022-09-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_rename_order_id_courierorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='cook_status',
            field=models.CharField(choices=[('PE', 'pending'), ('PIU', 'picked up'), ('OTW', 'on the way'), ('DE', 'delivered')], default='PE', max_length=25),
        ),
    ]
