# Generated by Django 3.2.13 on 2022-10-14 05:20

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0014_rename_cook_status_courierorder_courier_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCourierDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('File_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Document_file', models.FileField(blank=True, null=True, upload_to=core.utils.upload_path_handler)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
