# Generated by Django 3.2.13 on 2022-10-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0016_auto_20221014_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCourierDocuments',
            new_name='NewCourierDocument',
        ),
    ]
