# Generated by Django 3.2.13 on 2022-10-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0017_rename_newcourierdocuments_newcourierdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCourierDocument',
            new_name='NewCourierTrainingDocument',
        ),
    ]
