# Generated by Django 3.2.13 on 2022-11-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_is_cook_agree'),
        ('courier', '0018_rename_newcourierdocument_newcouriertrainingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='courierorder',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='courierorder',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_order_id', to='order.order'),
        ),
    ]
