# Generated by Django 3.2.13 on 2022-08-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_auto_20220602_1001'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cook_instruction', models.TextField(blank=True, null=True)),
                ('courier_instruction', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='initial', max_length=11)),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tip_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='amount', max_length=11)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='address.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.customer')),
            ],
            options={
                'db_table': 'table_order',
            },
        ),
    ]
