# Generated by Django 3.2.13 on 2022-08-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220728_0427'),
        ('order', '0002_ordermenuitem_ordermenusubitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart'),
        ),
    ]
