# Generated by Django 3.2.13 on 2022-08-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
