# Generated by Django 3.2.13 on 2022-09-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220602_1001'),
        ('cook', '0013_merge_20220727_1048'),
        ('address', '0001_initial'),
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='address.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='ordermenusubitem',
            name='menu_sub_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_sub_item', to='cook.menusubitem'),
        ),
    ]
