# Generated by Django 3.2.12 on 2022-10-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20221019_0617'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordermenuitem',
            table='table_order_menu_item',
        ),
        migrations.AlterModelTable(
            name='ordermenusubitem',
            table='table_order_menu_sub_item',
        ),
    ]
