# Generated by Django 3.2.12 on 2022-11-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20221019_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cook_agree',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
