# Generated by Django 3.2.13 on 2022-11-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addresscategory'),
        ('order', '0023_alter_order_is_cook_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='cook_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_order_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
