# Generated by Django 3.2.13 on 2022-05-31 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snippets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=11, null=True)),
                ('landmark', models.CharField(blank=True, max_length=110, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=110, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], max_length=110, null=True)),
                ('address_category', models.CharField(blank=True, choices=[('CSC', 'Communication Shared Courtyard'), ('CBC', 'Cubicle'), ('HCF', 'Hacienda / Farm'), ('HDD', 'House Detached'), ('HSD', 'House Semi-Detached'), ('OCM', 'Office or Commercial Mall'), ('OFB', 'Office Building'), ('OAP', 'Open Air / Park'), ('PWH', 'Plant / Warehouse'), ('RSB', 'Residential Building'), ('RSC', 'Residential Condominium')], max_length=110, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('country_id', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_address', to='snippets.country')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_address',
            },
        ),
    ]
