# Generated by Django 3.2.13 on 2023-02-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_addresscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=200)),
                ('card_number', models.IntegerField(max_length=20)),
                ('expiry_date', models.CharField(max_length=10)),
                ('cvv', models.ImageField(max_length=3, upload_to='')),
                ('save_card', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
