# Generated by Django 3.2.13 on 2023-02-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_addcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcard',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addcard',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
