# Generated by Django 3.2.13 on 2022-09-13 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_status'),
        ('customer', '0003_auto_20220602_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_order_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_status', models.CharField(choices=[('PE', 'pending'), ('CCU', 'customer canceled order')], default='PE', max_length=25)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_status', to='customer.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_status', to='order.order')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
