# Generated by Django 3.2.13 on 2022-09-05 05:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cook', '0013_merge_20220727_1048'),
        ('customer', '0003_auto_20220602_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_rating', to='cook.cook')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_rating_customer', to='customer.customer')),
            ],
            options={
                'db_table': 'table_cook_feedback',
                'unique_together': {('customer', 'cook')},
            },
        ),
    ]
