# Generated by Django 3.2.13 on 2022-09-07 04:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0014_auto_20220907_1004'),
        ('customer', '0003_auto_20220602_1001'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookfeedback',
            old_name='rating',
            new_name='star_rating',
        ),
        migrations.CreateModel(
            name='DishGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('star_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('like', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dislike', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('taste', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('use_of_ingredients', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('presentation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_grade_customer', to='customer.customer')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_grade_menu_item', to='cook.menuitem')),
            ],
            options={
                'db_table': 'table_dish_grade',
            },
        ),
    ]
